import { Utilisateur, Restaurant, Plat, Commande, LigneCommande, MissionLivraison, Signalement, HistoriqueAction } from '../src/types.js';

export const INITIAL_USERS: Utilisateur[] = [
  {
    id: 'USR-001',
    prenom: 'Julie',
    nom: 'Martin',
    email: 'julie.martin@example.com',
    telephone: '06 12 34 56 78',
    role: 'Client',
    adresse: '12 rue Oberkampf',
    code_postal: '75011',
    ville: 'Paris',
    instructions_livraison: 'Code 45B2, 3ème étage droite',
    compte_actif: true,
    statut_validation: 'Non requis',
  },
  {
    id: 'USR-002',
    prenom: 'Thomas',
    nom: 'Bernard',
    email: 'thomas.bernard@example.com',
    telephone: '06 98 76 54 32',
    role: 'Restaurateur',
    adresse: '18 rue de Charonne',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'Accepté',
  },
  {
    id: 'USR-003',
    prenom: 'Lucas',
    nom: 'Petit',
    email: 'lucas.petit@example.com',
    telephone: '06 45 67 89 01',
    role: 'Livreur',
    adresse: '5 rue de la Roquette',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'Accepté',
    disponible_livraison: true,
    moyen_deplacement: 'Vélo cargo électrique',
    zone_livraison: 'Paris 11e / Oberkampf / Bastille',
  },
  {
    id: 'USR-004',
    prenom: 'Claire',
    nom: 'Dubois',
    email: 'claire.dubois@example.com',
    telephone: '06 11 22 33 44',
    role: 'Administrateur',
    adresse: '2 boulevard Voltaire',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'Accepté',
  },
  {
    id: 'USR-005',
    prenom: 'Antoine',
    nom: 'Karam',
    email: 'antoine.karam@example.com',
    telephone: '06 22 33 44 55',
    role: 'Restaurateur',
    adresse: '34 rue Amelot',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'Accepté',
  },
  {
    id: 'USR-006',
    prenom: 'Mei',
    nom: 'Lin',
    email: 'mei.lin@example.com',
    telephone: '06 33 44 55 66',
    role: 'Restaurateur',
    adresse: '78 boulevard du Temple',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'Accepté',
  },
  {
    id: 'USR-007',
    prenom: 'Marc',
    nom: 'Dupont',
    email: 'marc.dupont@example.com',
    telephone: '06 44 55 66 77',
    role: 'Restaurateur',
    adresse: '15 rue Saint-Maur',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'Accepté',
  },
  {
    id: 'USR-008',
    prenom: 'Sophie',
    nom: 'Moreau',
    email: 'sophie.moreau@example.com',
    telephone: '06 55 66 77 88',
    role: 'Restaurateur',
    adresse: '22 avenue Parmentier',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'Accepté',
  },
  {
    id: 'USR-009',
    prenom: 'Karim',
    nom: 'Benali',
    email: 'karim.benali@example.com',
    telephone: '06 77 88 99 00',
    role: 'Livreur',
    adresse: '9 rue Folie-Méricourt',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'En attente',
    disponible_livraison: false,
    moyen_deplacement: 'Vélo de route',
    zone_livraison: 'Paris 10e / 11e',
  },
  {
    id: 'USR-010',
    prenom: 'Élodie',
    nom: 'Vidal',
    email: 'elodie.vidal@example.com',
    telephone: '06 88 99 00 11',
    role: 'Restaurateur',
    adresse: '45 rue de la Roquette',
    code_postal: '75011',
    ville: 'Paris',
    compte_actif: true,
    statut_validation: 'En attente',
  }
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'RST-001',
    nom: 'Trattoria Nonna',
    proprietaire_id: 'USR-002', // Thomas Bernard
    cuisine: 'Italien',
    description: 'Pâtes fraîches maison façonnées chaque matin et spécialités de Toscane.',
    adresse: '18 rue de Charonne',
    code_postal: '75011',
    ville: 'Paris',
    quartier: 'Bastille / Oberkampf',
    delai: '20–30 min',
    delai_min: 25,
    frais_livraison: 2.50,
    frais_service: 0.90,
    couleur: '#FFF1E5',
    photo: '/src/assets/images/foodup_trattoria_pasta_1790144540478.jpg',
    disponible: true,
    statut_validation: 'Accepté',
    horaires: '11:45 - 14:30 · 18:45 - 22:30',
  },
  {
    id: 'RST-002',
    nom: 'Le Comptoir Libanais',
    proprietaire_id: 'USR-005', // Antoine Karam
    cuisine: 'Libanais',
    description: 'Mezzés parfumés, falafels dorés minute et grillades au feu de bois.',
    adresse: '34 rue Amelot',
    code_postal: '75011',
    ville: 'Paris',
    quartier: 'Oberkampf',
    delai: '25–35 min',
    delai_min: 30,
    frais_livraison: 2.90,
    frais_service: 0.90,
    couleur: '#FFF8EE',
    photo: '/src/assets/images/foodup_libanais_mezze_1790144552489.jpg',
    disponible: true,
    statut_validation: 'Accepté',
    horaires: '12:00 - 15:00 · 19:00 - 23:00',
  },
  {
    id: 'RST-003',
    nom: 'Bao Street',
    proprietaire_id: 'USR-006', // Mei Lin
    cuisine: 'Asiatique',
    description: 'Baos ultra moelleux cuits vapeur et bouillons mijotés 12 heures.',
    adresse: '78 boulevard du Temple',
    code_postal: '75011',
    ville: 'Paris',
    quartier: 'République / Marais',
    delai: '15–25 min',
    delai_min: 20,
    frais_livraison: 1.90,
    frais_service: 0.90,
    couleur: '#E7F4EE',
    photo: '/src/assets/images/foodup_bao_street_1790144564187.jpg',
    disponible: true,
    statut_validation: 'Accepté',
    horaires: '11:30 - 14:30 · 18:30 - 22:30',
  },
  {
    id: 'RST-004',
    nom: 'Burger du Coin',
    proprietaire_id: 'USR-007', // Marc Dupont
    cuisine: 'Burgers',
    description: 'Burgers gourmets au boeuf de Normandie et frites maison taillées sur place.',
    adresse: '15 rue Saint-Maur',
    code_postal: '75011',
    ville: 'Paris',
    quartier: 'Saint-Maur / Voltaire',
    delai: '20–30 min',
    delai_min: 25,
    frais_livraison: 2.50,
    frais_service: 0.90,
    couleur: '#FFF1E5',
    photo: '/src/assets/images/foodup_burger_artisanal_1790144574781.jpg',
    disponible: true,
    statut_validation: 'Accepté',
    horaires: '12:00 - 14:30 · 19:00 - 23:00',
  },
  {
    id: 'RST-005',
    nom: 'Green Bowl',
    proprietaire_id: 'USR-008', // Sophie Moreau
    cuisine: 'Healthy',
    description: 'Bowls de saison équilibrés, graines bio et sauces faites maison.',
    adresse: '22 avenue Parmentier',
    code_postal: '75011',
    ville: 'Paris',
    quartier: 'Parmentier',
    delai: '15–20 min',
    delai_min: 18,
    frais_livraison: 1.90,
    frais_service: 0.90,
    couleur: '#E7F4EE',
    photo: '/src/assets/images/foodup_green_bowl_1790144586335.jpg',
    disponible: true,
    statut_validation: 'Accepté',
    horaires: '11:30 - 15:00 · 18:30 - 22:00',
  }
];

export const INITIAL_PLATS: Plat[] = [
  // Trattoria Nonna (RST-001)
  {
    id: 'PLT-001',
    restaurant_id: 'RST-001',
    nom: 'Tagliatelles au Ragoût mijoté',
    description: 'Pâtes fraîches maison, effiloché de boeuf confit au Chianti et parmesan 24 mois.',
    prix: 14.50,
    image_url: '/src/assets/images/foodup_trattoria_pasta_1790144540478.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-002',
    restaurant_id: 'RST-001',
    nom: 'Ravioli Ricotta & Épinards',
    description: 'Beurre noisette infusé à la sauge fraîche, noisettes du Piémont torréfiées.',
    prix: 13.90,
    image_url: '/src/assets/images/foodup_trattoria_pasta_1790144540478.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-003',
    restaurant_id: 'RST-001',
    nom: 'Tiramisu traditionnel maison',
    description: 'Biscuits cuillère imbibés d’espresso torréfié localement, mascarpone léger.',
    prix: 6.50,
    image_url: '/src/assets/images/foodup_trattoria_pasta_1790144540478.jpg',
    categorie: 'Desserts',
    disponible: true,
  },
  {
    id: 'PLT-004',
    restaurant_id: 'RST-001',
    nom: 'Limonade artisanale sicilienne',
    description: 'Citrons bio de Syracuse, menthe fraîche et sucre de canne léger (33cl).',
    prix: 3.80,
    image_url: '/src/assets/images/foodup_trattoria_pasta_1790144540478.jpg',
    categorie: 'Boissons',
    disponible: true,
  },

  // Le Comptoir Libanais (RST-002)
  {
    id: 'PLT-005',
    restaurant_id: 'RST-002',
    nom: 'Assiette Découverte Mezzés',
    description: 'Hummus crémeux, taboulé libanais authentique, 3 falafels chauds et pain pita.',
    prix: 15.00,
    image_url: '/src/assets/images/foodup_libanais_mezze_1790144552489.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-006',
    restaurant_id: 'RST-002',
    nom: 'Sandwich Chawarma Poulet Marinée',
    description: 'Broche marinée aux épices douces, crème d’ail toum maison et pickles de navet.',
    prix: 11.50,
    image_url: '/src/assets/images/foodup_libanais_mezze_1790144552489.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-007',
    restaurant_id: 'RST-002',
    nom: 'Baklawas assortis aux pistaches',
    description: 'Feuilletés croustillants au miel d’oranger et pistaches concassées (3 pièces).',
    prix: 5.50,
    image_url: '/src/assets/images/foodup_libanais_mezze_1790144552489.jpg',
    categorie: 'Desserts',
    disponible: true,
  },
  {
    id: 'PLT-008',
    restaurant_id: 'RST-002',
    nom: 'Jus de grenade pressé minute',
    description: '100% pur jus de grenade fraîche, sans sucre ajouté (25cl).',
    prix: 4.50,
    image_url: '/src/assets/images/foodup_libanais_mezze_1790144552489.jpg',
    categorie: 'Boissons',
    disponible: true,
  },

  // Bao Street (RST-003)
  {
    id: 'PLT-009',
    restaurant_id: 'RST-003',
    nom: 'Duo de Baos Porc Caramel',
    description: 'Deux buns vapeur moelleux, poitrine de porc fermier fondante, concombre et cacahuètes.',
    prix: 12.80,
    image_url: '/src/assets/images/foodup_bao_street_1790144564187.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-010',
    restaurant_id: 'RST-003',
    nom: 'Ramen Tonkotsu Traditionnel',
    description: 'Bouillon riche mijoté 12h, nouilles fraîches de blé, oeuf ajitsuke et chashu.',
    prix: 14.90,
    image_url: '/src/assets/images/foodup_bao_street_1790144564187.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-011',
    restaurant_id: 'RST-003',
    nom: 'Mochis glacés Thé Matcha (x2)',
    description: 'Pâte de riz gluante artisanale et coeur glacé au matcha d’Uji.',
    prix: 5.80,
    image_url: '/src/assets/images/foodup_bao_street_1790144564187.jpg',
    categorie: 'Desserts',
    disponible: true,
  },
  {
    id: 'PLT-012',
    restaurant_id: 'RST-003',
    nom: 'Thé glacé maison au jasmin & litchi',
    description: 'Infusion froide de fleurs de jasmin et purée de litchi (33cl).',
    prix: 4.20,
    image_url: '/src/assets/images/foodup_bao_street_1790144564187.jpg',
    categorie: 'Boissons',
    disponible: true,
  },

  // Burger du Coin (RST-004)
  {
    id: 'PLT-013',
    restaurant_id: 'RST-004',
    nom: 'Le Cheeseburger Fermier',
    description: 'Boeuf normand maturé haché minute, cheddar fermier AOP, oignons confits au cidre, frites incluses.',
    prix: 15.50,
    image_url: '/src/assets/images/foodup_burger_artisanal_1790144574781.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-014',
    restaurant_id: 'RST-004',
    nom: 'Portion de frites maison taillées',
    description: 'Pommes de terre Agria frites en deux bains, sel de Guérande et sauce fumée.',
    prix: 4.50,
    image_url: '/src/assets/images/foodup_burger_artisanal_1790144574781.jpg',
    categorie: 'Entrées',
    disponible: true,
  },
  {
    id: 'PLT-015',
    restaurant_id: 'RST-004',
    nom: 'Cookie chocolat noir & fleur de sel',
    description: 'Cuit minute, coeur fondant chocolat Valrhona et beurre demi-sel.',
    prix: 3.90,
    image_url: '/src/assets/images/foodup_burger_artisanal_1790144574781.jpg',
    categorie: 'Desserts',
    disponible: true,
  },

  // Green Bowl (RST-005)
  {
    id: 'PLT-016',
    restaurant_id: 'RST-005',
    nom: 'Superfood Quinoa & Avocat Bowl',
    description: 'Quinoa français, avocat Haas tranché, edamame bio, patate douce rôtie et vinaigrette sésame.',
    prix: 13.80,
    image_url: '/src/assets/images/foodup_green_bowl_1790144586335.jpg',
    categorie: 'Plats',
    disponible: true,
  },
  {
    id: 'PLT-017',
    restaurant_id: 'RST-005',
    nom: 'Carrot cake vegan aux noix',
    description: 'Farine complète, carottes râpées, cannelle d’Indonésie et glaçage cajou.',
    prix: 5.20,
    image_url: '/src/assets/images/foodup_green_bowl_1790144586335.jpg',
    categorie: 'Desserts',
    disponible: true,
  },
  {
    id: 'PLT-018',
    restaurant_id: 'RST-005',
    nom: 'Kombucha artisanal Gingembre',
    description: 'Brassé artisanalement en Île-de-France, probiotiques naturels (33cl).',
    prix: 4.80,
    image_url: '/src/assets/images/foodup_green_bowl_1790144586335.jpg',
    categorie: 'Boissons',
    disponible: true,
  }
];

export const INITIAL_COMMANDES: Commande[] = [
  {
    id: 'CMD-001',
    client_id: 'USR-001', // Julie Martin
    restaurant_id: 'RST-001', // Trattoria Nonna
    statut: 'En préparation',
    sous_total: 21.00,
    frais_livraison: 2.50,
    frais_service: 0.90,
    total: 24.40,
    adresse_livraison: '12 rue Oberkampf, 75011 Paris',
    instructions_livraison: 'Code 45B2, 3ème étage droite',
    temps_preparation_min: 20,
    paiement_simule: 'Validé',
    cree_a: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    mise_a_jour_a: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'CMD-002',
    client_id: 'USR-001', // Julie Martin
    restaurant_id: 'RST-002', // Le Comptoir Libanais
    statut: 'Livrée',
    sous_total: 20.50,
    frais_livraison: 2.90,
    frais_service: 0.90,
    total: 24.30,
    adresse_livraison: '12 rue Oberkampf, 75011 Paris',
    instructions_livraison: 'Code 45B2',
    livreur_id: 'USR-003', // Lucas Petit
    paiement_simule: 'Validé',
    cree_a: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    mise_a_jour_a: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_LIGNES: LigneCommande[] = [
  // Lignes pour CMD-001
  {
    id: 'LIG-001',
    commande_id: 'CMD-001',
    plat_id: 'PLT-001',
    nom_plat_enregistre: 'Tagliatelles au Ragoût mijoté',
    prix_unitaire_enregistre: 14.50,
    quantite: 1,
    total_ligne: 14.50,
  },
  {
    id: 'LIG-002',
    commande_id: 'CMD-001',
    plat_id: 'PLT-003',
    nom_plat_enregistre: 'Tiramisu traditionnel maison',
    prix_unitaire_enregistre: 6.50,
    quantite: 1,
    total_ligne: 6.50,
  },
  // Lignes pour CMD-002
  {
    id: 'LIG-003',
    commande_id: 'CMD-002',
    plat_id: 'PLT-005',
    nom_plat_enregistre: 'Assiette Découverte Mezzés',
    prix_unitaire_enregistre: 15.00,
    quantite: 1,
    total_ligne: 15.00,
  },
  {
    id: 'LIG-004',
    commande_id: 'CMD-002',
    plat_id: 'PLT-007',
    nom_plat_enregistre: 'Baklawas assortis aux pistaches',
    prix_unitaire_enregistre: 5.50,
    quantite: 1,
    total_ligne: 5.50,
  }
];

export const INITIAL_MISSIONS: MissionLivraison[] = [
  {
    id: 'MIS-001',
    commande_id: 'CMD-001',
    restaurant_id: 'RST-001',
    statut: 'Disponible',
    remuneration_annoncee: 5.40,
  },
  {
    id: 'MIS-002',
    commande_id: 'CMD-002',
    restaurant_id: 'RST-002',
    livreur_id: 'USR-003', // Lucas Petit
    statut: 'Terminée',
    remuneration_annoncee: 5.80,
    date_attribution: new Date(Date.now() - 23.8 * 60 * 60 * 1000).toISOString(),
    date_retrait: new Date(Date.now() - 23.5 * 60 * 60 * 1000).toISOString(),
    date_livraison: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_SIGNALEMENTS: Signalement[] = [
  {
    id: 'SIG-001',
    commande_id: 'CMD-002',
    auteur_id: 'USR-001', // Julie
    type: 'Retard',
    description: 'La commande est arrivée avec 10 minutes de retard mais la nourriture était encore bien chaude.',
    statut: 'Résolu',
    reponse_admin: 'Merci pour votre retour Julie, nous avons ajusté l’estimation du restaurant.',
    resolu_par: 'USR-004', // Claire
    cree_a: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_HISTORIQUE: HistoriqueAction[] = [
  {
    id: 'ACT-001',
    commande_id: 'CMD-002',
    acteur_id: 'USR-001',
    action: 'CREATION_COMMANDE',
    description: 'Julie Martin a validé la commande CMD-002 chez Le Comptoir Libanais.',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ACT-002',
    commande_id: 'CMD-002',
    acteur_id: 'USR-005',
    action: 'ACCEPTATION_RESTAURANT',
    description: 'Antoine Karam a accepté la commande CMD-002 (préparation 25 min).',
    date: new Date(Date.now() - 23.9 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ACT-003',
    commande_id: 'CMD-002',
    mission_id: 'MIS-002',
    acteur_id: 'USR-003',
    action: 'ACCEPTATION_LIVREUR',
    description: 'Lucas Petit a pris en charge la mission de livraison MIS-002.',
    date: new Date(Date.now() - 23.8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ACT-004',
    commande_id: 'CMD-002',
    mission_id: 'MIS-002',
    acteur_id: 'USR-003',
    action: 'COMMANDE_LIVREE',
    description: 'Lucas Petit a confirmé la livraison au client.',
    date: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ACT-005',
    commande_id: 'CMD-001',
    acteur_id: 'USR-001',
    action: 'CREATION_COMMANDE',
    description: 'Julie Martin a passé la commande CMD-001 chez Trattoria Nonna.',
    date: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'ACT-006',
    commande_id: 'CMD-001',
    acteur_id: 'USR-002',
    action: 'ACCEPTATION_RESTAURANT',
    description: 'Thomas Bernard a accepté la commande CMD-001 (préparation estimée 20 min).',
    date: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  }
];
